### ISSUE TITLE
 Sometimes cannot get information from some devices.

### ISSUE THREAD

**Issue by zhangming170622** [seventhmoon/ipapi-retrofit#10]
Hi, Thank you very much for providing us with good library.
But sometimes cannot get information from some devices such as "Android SHARP SHV39  8.0.0".
If the first two times do not get the information and run it again, then success to get information.
Is this error?  I want to your help.

**Comment by seventhmoon** [comment]
Could you provide more information or the logcat?
I believe it is because of the rate control from the service provider.

**Comment by zhangming170622** [comment]
Hi, Of course your library is very good.
I usually get needed information. Really sometimes I don't get IP address.
If I try again, then get IP address.
Have you ever been like this?
Now I'am trying more information or the log.
Could you explain about "the rate control from the service provider."?
I want to your kind help.

**Comment by seventhmoon** [comment]
It is explained here: http://ip-api.com/docs/

**Comment by zhangming170622** [comment]
Thank you very much.
You are very kind.
I found exactly what caused the problem.
