### ISSUE TITLE
It is still working?!

### ISSUE THREAD

**Issue by MML-Pro** [seventhmoon/ipapi-retrofit#12]
I tried the code as descried but I didn't get any response or even error!

**Comment by ghasem110deh** [comment]
hi, thank for this
for me work done ... but don't response lat & lng (location)

**Comment by seventhmoon** [comment]
Which version you are using?

**Comment by MML-Pro** [comment]
> Which version you are using?
the last version 1.44,
 Thanks for replay It's working now with "Toast" it's seems the problem with logging in android studio, I tried to use different types of logging but all not working and I don't know why!
