### ISSUE TITLE
Can't get timezone.. please fix

### ISSUE THREAD

**Issue by AhmadullahSaikat** [seventhmoon/ipapi-retrofit#3]
When I print timezone it print's "Asia/Dhaka". 
But it needs to be +6.00. 
Please fix this issue.

**Comment by seventhmoon** [comment]
The information is from the upstream provider http://ip-api.com/json, and it is an expected output.

You could use [Jodatime](http://www.joda.org/joda-time/userguide.html#TimeZones) to get the offset.
